#!/usr/bin/env bash
# staging-provision.sh - Provision Docker Compose staging environment for testing
# Part of Spec Kit - https://github.com/Anthroware/spec-kit
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Defaults
SERVICES="postgres,redis"
SKIP_PLAYWRIGHT=false
RESET=false
STATUS_ONLY=false
DOWN=false
JSON_OUTPUT=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --services)
      SERVICES="$2"
      shift 2
      ;;
    --skip-playwright)
      SKIP_PLAYWRIGHT=true
      shift
      ;;
    --reset)
      RESET=true
      shift
      ;;
    --status)
      STATUS_ONLY=true
      shift
      ;;
    --down)
      DOWN=true
      shift
      ;;
    --json)
      JSON_OUTPUT=true
      shift
      ;;
    -h|--help)
      echo "Usage: staging-provision.sh [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --services <list>    Services to provision (default: postgres,redis)"
      echo "  --skip-playwright    Skip Playwright container"
      echo "  --reset              Tear down and recreate all services"
      echo "  --status             Show current status only"
      echo "  --down               Stop all staging services"
      echo "  --json               Output results as JSON"
      echo "  -h, --help           Show this help"
      exit 0
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      exit 1
      ;;
  esac
done

# Detect project root
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
STAGING_DIR="$PROJECT_ROOT/.speckit/staging"
STATE_DIR="$PROJECT_ROOT/.speckit/state/staging"

# Check Docker is running
check_docker() {
  if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}ERROR: Docker is not running${NC}"
    echo "Please start Docker Desktop and try again"
    exit 1
  fi

  # Check docker-compose (v1 or v2)
  if docker compose version > /dev/null 2>&1; then
    DOCKER_COMPOSE="docker compose"
  elif docker-compose --version > /dev/null 2>&1; then
    DOCKER_COMPOSE="docker-compose"
  else
    echo -e "${RED}ERROR: docker-compose not found${NC}"
    echo "Please install Docker Compose and try again"
    exit 1
  fi
}

# Create docker-compose.yaml
create_compose_file() {
  mkdir -p "$STAGING_DIR"

  cat > "$STAGING_DIR/docker-compose.yaml" << 'EOF'
version: '3.8'

services:
  test-db:
    image: postgres:16-alpine
    container_name: speckit-test-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - test-db-data:/var/lib/postgresql/data

  test-redis:
    image: redis:7-alpine
    container_name: speckit-test-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - redis

  playwright:
    image: mcr.microsoft.com/playwright:v1.40.0-jammy
    container_name: speckit-playwright
    working_dir: /app
    volumes:
      - ../..:/app
    environment:
      - CI=true
    profiles:
      - e2e
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      test-db:
        condition: service_healthy

volumes:
  test-db-data:

networks:
  default:
    name: speckit-staging
EOF

  echo -e "${GREEN}Created docker-compose.yaml${NC}"
}

# Create test-config.env
create_config_file() {
  cat > "$STAGING_DIR/test-config.env" << 'EOF'
# Auto-generated by /speckit.staging - DO NOT EDIT
# Staging environment configuration for tests

# Database
DATABASE_URL=postgresql://test:test@localhost:5433/test_db
TEST_DATABASE_HOST=localhost
TEST_DATABASE_PORT=5433
TEST_DATABASE_USER=test
TEST_DATABASE_PASSWORD=test
TEST_DATABASE_NAME=test_db

# Redis
REDIS_URL=redis://localhost:6380
TEST_REDIS_HOST=localhost
TEST_REDIS_PORT=6380

# Playwright
PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
CI=true

# Test Configuration
NODE_ENV=test
LOG_LEVEL=error
EOF

  echo -e "${GREEN}Created test-config.env${NC}"
}

# Build compose profiles from services
build_profiles() {
  local profiles=""

  IFS=',' read -ra SERVICE_ARRAY <<< "$SERVICES"
  for service in "${SERVICE_ARRAY[@]}"; do
    case "$service" in
      redis)
        profiles="${profiles:+$profiles,}redis"
        ;;
      playwright)
        if [ "$SKIP_PLAYWRIGHT" = false ]; then
          profiles="${profiles:+$profiles,}e2e"
        fi
        ;;
    esac
  done

  echo "$profiles"
}

# Check service health
check_health() {
  local service=$1
  local container=$2

  if docker ps --filter "name=$container" --filter "health=healthy" --format "{{.Names}}" | grep -q "$container"; then
    return 0
  fi
  return 1
}

# Wait for all services to be healthy
wait_for_healthy() {
  local max_wait=60
  local waited=0

  echo -e "${BLUE}Waiting for services to be healthy...${NC}"

  while [ $waited -lt $max_wait ]; do
    local all_healthy=true

    # Check postgres (always required)
    if check_health "postgres" "speckit-test-db"; then
      echo -e "  ${GREEN}postgres: healthy${NC}"
    else
      all_healthy=false
    fi

    # Check redis if enabled
    if [[ "$SERVICES" == *"redis"* ]]; then
      if check_health "redis" "speckit-test-redis"; then
        echo -e "  ${GREEN}redis: healthy${NC}"
      else
        all_healthy=false
      fi
    fi

    if [ "$all_healthy" = true ]; then
      return 0
    fi

    sleep 2
    waited=$((waited + 2))
  done

  echo -e "${RED}ERROR: Services did not become healthy within ${max_wait}s${NC}"
  $DOCKER_COMPOSE -f "$STAGING_DIR/docker-compose.yaml" logs
  return 1
}

# Validate QG-STAGING-001
validate_gate() {
  echo -e "\n${BLUE}Validating QG-STAGING-001: Staging Environment Ready${NC}"

  local all_passed=true
  local checks=()

  # Check PostgreSQL
  if docker exec speckit-test-db pg_isready -U test -d test_db > /dev/null 2>&1; then
    checks+=("postgres:PASS:5433")
    echo -e "  ${GREEN}PostgreSQL: PASS${NC}"
  else
    checks+=("postgres:FAIL:5433")
    echo -e "  ${RED}PostgreSQL: FAIL${NC}"
    all_passed=false
  fi

  # Check Redis if enabled
  if [[ "$SERVICES" == *"redis"* ]]; then
    if docker exec speckit-test-redis redis-cli ping 2>/dev/null | grep -q "PONG"; then
      checks+=("redis:PASS:6380")
      echo -e "  ${GREEN}Redis: PASS${NC}"
    else
      checks+=("redis:FAIL:6380")
      echo -e "  ${RED}Redis: FAIL${NC}"
      all_passed=false
    fi
  fi

  # Check Playwright if enabled
  if [[ "$SERVICES" == *"playwright"* ]] && [ "$SKIP_PLAYWRIGHT" = false ]; then
    if docker ps --filter "name=speckit-playwright" --format "{{.Names}}" | grep -q "speckit-playwright"; then
      checks+=("playwright:PASS:0")
      echo -e "  ${GREEN}Playwright: PASS${NC}"
    else
      checks+=("playwright:FAIL:0")
      echo -e "  ${RED}Playwright: FAIL${NC}"
      all_passed=false
    fi
  fi

  if [ "$all_passed" = true ]; then
    echo -e "\n${GREEN}QG-STAGING-001: PASSED${NC}"
    return 0
  else
    echo -e "\n${RED}QG-STAGING-001: FAILED${NC}"
    return 1
  fi
}

# Write staging state
write_state() {
  mkdir -p "$STATE_DIR"

  local redis_healthy=false
  local playwright_enabled=false

  if [[ "$SERVICES" == *"redis"* ]]; then
    redis_healthy=true
  fi

  if [[ "$SERVICES" == *"playwright"* ]] && [ "$SKIP_PLAYWRIGHT" = false ]; then
    playwright_enabled=true
  fi

  cat > "$STATE_DIR/staging-status.json" << EOF
{
  "status": "ready",
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "services": {
    "postgres": {"port": 5433, "healthy": true},
    "redis": {"port": 6380, "healthy": $redis_healthy},
    "playwright": {"enabled": $playwright_enabled}
  },
  "gate": {
    "QG-STAGING-001": "PASSED"
  }
}
EOF
}

# Show status
show_status() {
  echo -e "${BLUE}Staging Environment Status${NC}"
  echo ""

  if [ -f "$STAGING_DIR/docker-compose.yaml" ]; then
    $DOCKER_COMPOSE -f "$STAGING_DIR/docker-compose.yaml" ps
  else
    echo "No staging environment found. Run without --status to create one."
  fi

  if [ -f "$STATE_DIR/staging-status.json" ]; then
    echo ""
    echo -e "${BLUE}Last State:${NC}"
    cat "$STATE_DIR/staging-status.json"
  fi
}

# Stop services
stop_services() {
  echo -e "${YELLOW}Stopping staging services...${NC}"

  if [ -f "$STAGING_DIR/docker-compose.yaml" ]; then
    $DOCKER_COMPOSE -f "$STAGING_DIR/docker-compose.yaml" down -v
    echo -e "${GREEN}Staging services stopped and volumes removed${NC}"
  else
    echo "No staging environment found."
  fi

  # Clean up state
  rm -f "$STATE_DIR/staging-status.json"
}

# Output JSON
output_json() {
  cat << EOF
{
  "FEATURE_DIR": "$(pwd)",
  "PROJECT_ROOT": "$PROJECT_ROOT",
  "STAGING_DIR": "$STAGING_DIR",
  "COMPOSE_FILE": "$STAGING_DIR/docker-compose.yaml",
  "CONFIG_FILE": "$STAGING_DIR/test-config.env",
  "DATABASE_URL": "postgresql://test:test@localhost:5433/test_db",
  "REDIS_URL": "redis://localhost:6380"
}
EOF
}

# Main execution
main() {
  check_docker

  # JSON output mode
  if [ "$JSON_OUTPUT" = true ]; then
    output_json
    exit 0
  fi

  # Status only
  if [ "$STATUS_ONLY" = true ]; then
    show_status
    exit 0
  fi

  # Stop services
  if [ "$DOWN" = true ]; then
    stop_services
    exit 0
  fi

  echo -e "${BLUE}Provisioning Staging Environment${NC}"
  echo ""

  # Reset if requested
  if [ "$RESET" = true ]; then
    echo -e "${YELLOW}Resetting staging environment...${NC}"
    stop_services
  fi

  # Create configuration files
  create_compose_file
  create_config_file

  # Build profiles
  COMPOSE_PROFILES=$(build_profiles)

  # Start services
  echo -e "\n${BLUE}Starting services...${NC}"
  if [ -n "$COMPOSE_PROFILES" ]; then
    COMPOSE_PROFILES=$COMPOSE_PROFILES $DOCKER_COMPOSE -f "$STAGING_DIR/docker-compose.yaml" up -d
  else
    $DOCKER_COMPOSE -f "$STAGING_DIR/docker-compose.yaml" up -d
  fi

  # Wait for health
  if ! wait_for_healthy; then
    exit 1
  fi

  # Validate gate
  if ! validate_gate; then
    exit 1
  fi

  # Write state
  write_state

  # Success summary
  echo ""
  echo -e "${GREEN}========================================${NC}"
  echo -e "${GREEN}Staging Environment Ready${NC}"
  echo -e "${GREEN}========================================${NC}"
  echo ""
  echo "Configuration files:"
  echo "  - Docker Compose: $STAGING_DIR/docker-compose.yaml"
  echo "  - Test Config:    $STAGING_DIR/test-config.env"
  echo ""
  echo "Usage:"
  echo "  source $STAGING_DIR/test-config.env"
  echo "  npm test"
  echo ""
  echo "Commands:"
  echo "  /speckit.staging --status    Check status"
  echo "  /speckit.staging --down      Stop services"
  echo "  /speckit.staging --reset     Recreate services"
  echo ""
  echo -e "${GREEN}Next: Run /speckit.implement to start TDD implementation${NC}"
}

main "$@"
